Fun_Appointement/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fun_Appointement;
using Newtonsoft.Json;

namespace Fun_Appointement.Controllers
{
    public class ActivitiesController : Controller
    {
        private Fun_Appointement_DBModel db = new Fun_Appointement_DBModel();

        // GET: Activities
        public async Task<ActionResult> Index()
        {
            var activities = db.Activities.Include(a => a.TypeActivity);
            return View(await activities.ToListAsync());
        }





        // GET: Activities/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = await db.Activities.FindAsync(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // GET: Activities/Create
        public ActionResult Create()
        {
            ViewBag.IDTypeActivity = new SelectList(db.TypeActivities, "IDTypeActivity", "Name");
            return View();
        }

        // POST: Activities/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "IDActivity,Date,IDTypeActivity,Street,PostalCode,City,End")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Activities.Add(activity);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.IDTypeActivity = new SelectList(db.TypeActivities, "IDTypeActivity", "Name", activity.IDTypeActivity);
            return View(activity);
        }


        // GET: Activities/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = await db.Activities.FindAsync(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDTypeActivity = new SelectList(db.TypeActivities, "IDTypeActivity", "Name", activity.IDTypeActivity);
            return View(activity);
        }

        // POST: Activities/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "IDActivity,Date,IDTypeActivity,Street,PostalCode,City,End")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activity).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.IDTypeActivity = new SelectList(db.TypeActivities, "IDTypeActivity", "Name", activity.IDTypeActivity);
            return View(activity);
        }

        // GET: Activities/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = await db.Activities.FindAsync(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: Activities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Activity activity = await db.Activities.FindAsync(id);
            db.Activities.Remove(activity);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult GetEvents()
        {
            using (Fun_Appointement_DBModel dc = new Fun_Appointement_DBModel())
            {
                var activities = db.Activities.Include(a => a.TypeActivity).ToList();
                List<ActivityForJson> result = new List<ActivityForJson>();

                foreach (var elem in activities)
                {
                    ActivityForJson temp = new ActivityForJson();
                    temp.ActivityName = elem.TypeActivity.Name;
                    temp.City = elem.City;
                    temp.Date = elem.Date;
                    temp.IDActivity = elem.IDActivity;
                    temp.End = elem.End;
                    temp.PostalCode = elem.PostalCode;
                    temp.Street = elem.Street;
                    //temp.Validated = elem.Validated;
                    result.Add(temp);
                }

                var str = JsonConvert.SerializeObject(result);
                LogHelper.WriteToFile(str, "list event");
                return Json(result, JsonRequestBehavior.AllowGet);

            }
        }

        [HttpPost]
        public ActionResult SaveEvent(ActivityForJson a)
        {

            using (Fun_Appointement_DBModel dc = new Fun_Appointement_DBModel())
            {
                
                var b = new Activity()
                {
                    IDTypeActivity = 1,
                    City = a.City,
                    Date = a.Date,
                    IDActivity = a.IDActivity,
                    End = a.End,
                    PostalCode = a.PostalCode,
                    Street = a.Street
                };
                //LogHelper.WriteToFile("rer", "save event");
                dc.Activities.Add(b);
                dc.SaveChanges();
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
        }

        [HttpPost]
        public ActionResult DeleteEvent(int IDActivity)
        {
            var status = false;
            using (Fun_Appointement_DBModel dc = new Fun_Appointement_DBModel())
            {
                var v = dc.Activities.Where(z => z.IDActivity == IDActivity).FirstOrDefault();
                if (v != null)
                {
                    dc.Activities.Remove(v);
                    dc.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }
    }
    public class ActivityForJson
    {
        public int IDActivity { get; set; }
        public DateTime Date { get; set; }
        //public bool Validated { get; set; }
        public int IDTypeActivity { get; set; }
        public string Street { get; set; }
        public int PostalCode { get; set; }
        public string City { get; set; }
        public string ActivityName { get; set; }
        public DateTime? End { get; set; }

    }
}

Fun_Appointement/Controllers/AuthentificationController.cs
using Fun_Appointement;
using Fun_Appointement.Controllers;
using Fun_Appointement.Models;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

namespace WebApplication1.Controllers
{
    public class AuthentificationController : Controller
    {
        // GET: Authentification
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User user)
        {
            if (user.Pseudo != null || user.Password != null)
            {
                using (var context = new Fun_Appointement_DBModel())
                {
                    if (context.Users.Any(n => n.Pseudo == user.Pseudo && n.Password == user.Password))
                    {
                        var connectedUser = context.Users.FirstOrDefault(n => n.Pseudo == user.Pseudo && n.Password == user.Password);
                        FormsAuthentication.SetAuthCookie(connectedUser.IDUser.ToString(), true);
                        HomeController.ConnectedUserID = connectedUser.IDUser;
                        HomeController.ConnectedPseudo = connectedUser.Pseudo;
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ViewBag.Message = "Identifiant/MDP incorrects";
                        return View("Login");
                    }
                }
            }
            else
            {
                ViewBag.Message = "Veuillez remplir les champs";
                return View("Login");
            }
        }
        public ActionResult Disconnect(string url)
        {
            HomeController.ConnectedUserID = null;
            HomeController.ConnectedPseudo = null;
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

    }
}

Fun_Appointement/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fun_Appointement;
using Newtonsoft.Json;

namespace FunAppointement.Controllers
{
    public class CalendarController : Controller
    {
        // GET: Calendar
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetActivitiesByUserByDate(DateTime datedeb, DateTime datefin)
        {
            var IDUser = Fun_Appointement.Controllers.HomeController.ConnectedPseudo;
            using (var context = new Fun_Appointement_DBModel())
            {
                var listActivite = context.Activities.Include(a => a.TypeActivity).Include(a => a.Users)
                    .Where(a => a.Date <= datedeb && a.Date <= datefin)
                    .ToList();
                List<JsonActivityByUserByDate> result = new List<JsonActivityByUserByDate>();
                foreach (var elem in listActivite)
                {
                    var temp = new JsonActivityByUserByDate();
                    temp.IDActivity = elem.IDActivity;
                    temp.Plage = elem.Plage;
                    temp.Date = elem.Date;
                    temp.Validated = elem.Validated;
                    temp.Street = elem.Street;
                    temp.PostalCode = elem.IDActivity;
                    temp.City = elem.City;
                    temp.ActivityName = elem.TypeActivity.Name;
                    foreach (var user in elem.Users)
                    { temp.pseudos.Add(user.Pseudo); }
                    result.Add(temp);

                }
                   LogHelper.WriteToFile(JsonConvert.SerializeObject(result),nameof(this.ToString));
                return Json(result, JsonRequestBehavior.AllowGet);

            }
        }
    }
    public class JsonActivityByUserByDate
    {
        public int IDActivity { get; set; }
        public int Plage { get; set; }
        public DateTime Date { get; set; }
        public bool Validated { get; set; }
        public string Street { get; set; }
        public int PostalCode { get; set; }
        public string City { get; set; }
        public string ActivityName { get; set; }
        public List<string> pseudos { get; set; }
    }
}

Fun_Appointement/Controllers/TypeActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fun_Appointement;

namespace Fun_Appointement.Controllers
{
    public class TypeActivitiesController : Controller
    {
        private Fun_Appointement_DBModel db = new Fun_Appointement_DBModel();

        // GET: TypeActivities
        public async Task<ActionResult> Index()
        {
            return View(await db.TypeActivities.ToListAsync());
        }

        // GET: TypeActivities/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeActivity typeActivity = await db.TypeActivities.FindAsync(id);
            if (typeActivity == null)
            {
                return HttpNotFound();
            }
            return View(typeActivity);
        }

        // GET: TypeActivities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TypeActivities/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "IDTypeActivity,Name,MinUser,MaxUser,IDUser")] TypeActivity typeActivity)
        {
            if (ModelState.IsValid)
            {
                db.TypeActivities.Add(typeActivity);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(typeActivity);
        }

        // GET: TypeActivities/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeActivity typeActivity = await db.TypeActivities.FindAsync(id);
            if (typeActivity == null)
            {
                return HttpNotFound();
            }
            return View(typeActivity);
        }

        // POST: TypeActivities/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "IDTypeActivity,Name,MinUser,MaxUser,IDUser")] TypeActivity typeActivity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(typeActivity).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(typeActivity);
        }

        // GET: TypeActivities/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeActivity typeActivity = await db.TypeActivities.FindAsync(id);
            if (typeActivity == null)
            {
                return HttpNotFound();
            }
            return View(typeActivity);
        }

        // POST: TypeActivities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            TypeActivity typeActivity = await db.TypeActivities.FindAsync(id);
            db.TypeActivities.Remove(typeActivity);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

    
    
}

Fun_Appointement/Views/Shared/CalendarView.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FunAppointement</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("~/Views/Shared/_BarreMenu.cshtml");
    @RenderSection("scripts", required: false)
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - A WLR Product</p>
        </footer>
    </div>
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><span id="eventTitle"></span></h4>
                </div>
                <div class="modal-body">
                    <button id="btnDelete" class="btn btn-default btn-sm pull-right">
                        <span class="glyphicon glyphicon-remove"></span> Effacer
                    </button>
                    <button id="btnEdit" class="btn btn-default btn-sm pull-right" style="margin-right:5px;">
                        <span class="glyphicon glyphicon-pencil"></span> Edit
                    </button>
                    <p id="pDetails"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div id="myModalSave" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Enregistrement de l'Event</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal">
                        <input type="hidden" id="hdEventID" value="0" />
                        <select type="hidden" id="hdIDTypeActivity" value="1" />
                        
                        <div class="form-group">
                            <label>Activités</label>
                            <input type="text" id="txtSubject" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Début</label>
                            <div class="input-group date" id="dtp1">
                                <input type="text" id="txtStart" class="form-control" />

                            </div>
                            <label>Fin</label>
                            <div class="input-group date" id="dtp2">
                                <input type="text" id="txtEnd" class="form-control" />

                            </div>
                        </div>
                        <div class="form-group">
                            <label>Adresse</label>
                            <textarea id="txtStreet" rows="1" class="form-control"></textarea>
                            <textarea id="txtPostalCode" rows="1" class="form-control"></textarea>
                            <textarea id="txtCity" rows="1" class="form-control"></textarea>
                        </div>

                        <button type="button" id="btnSave" class="btn btn-success">Enregistrer</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Scripts", false)
    <link rel='stylesheet' href='~/Content/fullcalendar.css' />
    <script src='~/Scripts/lib/moment.min.js'></script>
    <script src='~/Scripts/fullcalendar.js'></script>
    <script src='~/Scripts/locale-all.js'></script>

</body>

</html>
<script>
    $(document).ready(function () {
        var events = [];
        var selectedEvent = null;
        FetchEventAndRenderCalendar();
        function FetchEventAndRenderCalendar() {
            events = [];
            $.ajax({
                type: "GET",
                url: "/Activities/GetEvents",
                success: function (data) {
                    $.each(data, function (i, v) {
                        events.push({
                            eventID: v.IDActivity,
                            type: v.IDTypeActivity,
                            title: v.ActivityName,
                            start: moment(v.Date),
                            end: v.End != null ? moment(v.End) : null,
                            street: v.Street,
                            postalcode: v.PostalCode,
                            city: v.City,

                        });
                    })

                    GenerateCalender(events);
                },
                error: function (error) {
                    alert('failed');
                }
            })

            function GenerateCalender(events) {
                $('#calendar').fullCalendar('destroy');
                $('#calendar').fullCalendar({
                    schedulerLicenseKey: 'CC-Attribution-NonCommercial-NoDerivatives',
                    refetchResourcesOnNavigate: true,
                    selectable: true,
                    selectHelper: true,
                    allDay: false,
                    defaultView: 'agendaWeek',
                    locale: 'fr',
                    aspectRatio: 2,
                    slotDuration: '01:00:00',
                    minTime: '08:00:00',
                    maxTime: '24:00:00',
                    forceEventDuration: true,
                    defaultTimedEventDuration: '02:00:00',
                    Duration: '02:00:00',
                    groupByDateAndResource: true,
                    timeFormat: 'HH:mm',
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'month,basicDay,agenda'
                    },
                    eventColor: '#56d39f',
                    events: events,
                    eventClick: function (calEvent, jsEvent, view) {
                        selectedEvent = calEvent;
                        $('#myModal #eventTitle').text(calEvent.title);
                        var $title = $('<div/>');
                        $title.append($('<p/>').html('<b>Start:</b>' + calEvent.start.format("DD-MMM-YYYY HH:mm")));
                        if (calEvent.end != null) {
                            $title.append($('<p/>').html('<b>End:</b>' + calEvent.end.format("DD-MMM-YYYY HH:mm")));
                        }
                        $title.append($('<p/>').html('<b>Lieu:</b>' + calEvent.city));
                        $('#myModal #pDetails').empty().html($title);

                        $('#myModal').modal();
                    },
                    selectable: true,
                    select: function (start, end) {
                        selectedEvent = {
                            eventID: 0,
                            IDTypeActivity: 1,
                            title: '',
                            start: start,
                            end: end,
                            street: '',
                            postalcode: '',
                            city: '',

                        };
                        openAddEditForm();
                        $('#calendar').fullCalendar('unselect');
                    },
                    editable: true,
                    eventDrop: function (event) {
                        var data = {
                            eventID: event.eventID,
                            type: event.IDTypeActivity,
                            Subject: event.title,
                            Start: event.start.format('DD/MM/YYYY HH:mm'),
                            End: event.end != null ? event.end.format('DD/MM/YYYY HH:mm') : null,
                            Street: event.street,
                            PostalCode: event.postalcode,
                            City: event.city

                        };
                        SaveEvent(data);
                        
                    }
                })
            }

            $('#btnEdit').click(function () {
                //Open modal dialog for edit event
                openAddEditForm();
            })
            $('#btnDelete').click(function () {
                if (selectedEvent != null && confirm('Are you sure?')) {
                    $.ajax({
                        type: "POST",
                        url: '/Activities/DeleteEvent',
                        data: { 'IDActivity': selectedEvent.eventID },
                        success: function (data) {
                            if (data.status) {
                                $('#myModal').modal('hide');
                                FetchEventAndRenderCalendar();

                            }
                        },
                        error: function () {
                            alert('Failed');
                        }
                    })
                }
            })
                ;
                
            function openAddEditForm() {
                if (selectedEvent != null) {
                    $('#hdIDActivity').val(selectedEvent.eventID);
                    $('#hdIDTypeActivity').val(selectedEvent.IDTypeActivity);
                    $('#txtSubject').val(selectedEvent.title);
                    $('#txtStart').val(selectedEvent.start.format('DD/MM/YYYY HH:mm'));
                    $('#txtEnd').val(selectedEvent.end != null ? selectedEvent.end.format('DD/MM/YYYY HH:mm') : '');
                    $('#txtStreet').val(selectedEvent.street);
                    $('#txtPostalCode').val(selectedEvent.postalcode);
                    $('#txtCity').val(selectedEvent.city);

                }
                $('#myModal').modal('hide');
                $('#myModalSave').modal();
            }
            $('#btnSave').click(function () {
                
                if ($('#txtSubject').val().trim() == "") {
                    alert('Subject required');
                    return;
                }
                if ($('#txtStart').val().trim() == "") {
                    alert('Start date required');
                    return;
                }
                if ($('#txtEnd').val().trim() == "") {

                    alert('End date required');
                    return;
                }
                else {
                    var startDate = moment($('#txtStart').val(), "DD/MM/YYYY HH:mm").toDate();
                    var endDate = moment($('#txtEnd').val(), "DD/MM/YYYY HH:mm").toDate();
                    if (startDate > endDate) {
                        alert('Invalid end date');
                        return;
                    }
                }

                var data = {
                    IDTypeActivity: $('#hdIDTypeActivity').val(),
                    //IDActivity: $('#hdIDActivity').val(),
                    ActivityName: $('#txtSubject').val().trim(),
                    Date: $('#txtStart').val().trim(),
                    End: $('#txtEnd').val().trim(),
                    Street: $('#txtStreet').val(),
                    PostalCode: $('#txtPostalCode').val(),
                    City: $('#txtCity').val()

                }
                SaveEvent(data);
                $('#myModalSave').modal('hide');
            })
            function SaveEvent(data) {
                $.ajax({
                    type: "POST",
                    url: '/Activities/SaveEvent',
                    data: data,
                    success: function (data) {
                        if (data.status) {
                            alert('FAITTTTTT');
                            FetchEventAndRenderCalendar();
                            $('#myModalSave').modal('hide');
                            
                        }
                    },
                    error: function () {
                        $('#myModalSave').modal('hide');
                        alert('Failed');
                    }
                })
            }
        }
    });

</script>

Fun_Appointement/Views/Shared/_BarreMenu.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Retour Accueil", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (Fun_Appointement.Controllers.HomeController.ConnectedPseudo == "admin")
                {
                    <li class="text-uppercase">@Html.ActionLink("Gestion des comptes", "Index", "Users")</li>
                }
                else
                {
                    <li>@Html.ActionLink("Utilisateurs", "Index", "Users")</li>
                }
                <li>@Html.ActionLink("Types d'activités", "Index", "TypeActivities")</li>
                <li>@Html.ActionLink("Calendrier", "Index", "Calendar")</li>
                @if (Request.IsAuthenticated)
                {
                    <li> - </li>
                    <li>@Html.ActionLink($"Deconnexion ({Fun_Appointement.Controllers.HomeController.ConnectedPseudo})", "Disconnect", "Authentification")</li>
                }
                <li>@Html.ActionLink(".", "Create", "Activities")</li>

            </ul>
        </div>
    </div>
</div>

Fun_Appointement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FunAppointement</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @Html.Partial("~/Views/Shared/_BarreMenu.cshtml");

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Fun Appointement</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>